name: pangeo-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipywidgets
  - ipyleaflet
  - pandas
  - numpy
  - xarray
  - dask
  - distributed
  - nbserverproxy
  - jupyter
  - jupyterlab
  - zarr
  - intake
  - intake-xarray
  - graphviz
  - dask-kubernetes
  - tornado
  - python-wget
  - matplotlib
  - gcsfs
  - dask-labextension
  - pip
  - pip:
    - git+https://github.com/pangeo-data/rechunker.git#egg=rechunker
